In [376]:
import numpy as np

In [377]:
mylist = [1,2,3]

In [378]:
type(mylist)

list

In [379]:
np.array(mylist)

array([1, 2, 3])

In [380]:
mylist = np.array(mylist)

In [381]:
mylist

array([1, 2, 3])

In [382]:
type(mylist)

numpy.ndarray

In [383]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [384]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [385]:
mymatrix = np.array(mylist)

In [386]:
mymatrix.shape

(3, 3)

In [387]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [388]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [389]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [390]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [391]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [392]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [393]:
np.ones((5,5)) + 3

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [394]:
np.linspace(1,11,4)

array([ 1.        ,  4.33333333,  7.66666667, 11.        ])

In [395]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [396]:
np.random.rand(1)

array([0.73481906])

In [397]:
np.random.rand(4)

array([0.54196177, 0.91315356, 0.80792015, 0.40299783])

In [398]:
np.random.rand(5,5)

array([[0.35722434, 0.95287671, 0.34363158, 0.86509982, 0.83027771],
       [0.53816145, 0.92246937, 0.09714648, 0.10284749, 0.7015073 ],
       [0.89047987, 0.1595603 , 0.27557254, 0.67249153, 0.16430312],
       [0.70137114, 0.48763522, 0.68067777, 0.52154819, 0.04339669],
       [0.2239366 , 0.57520509, 0.12043366, 0.50011671, 0.13800957]])

In [399]:
np.random.randn(10)

array([ 1.02598415, -0.1565979 , -0.03157914,  0.64982583,  2.15484644,
       -0.61025886, -0.75532534, -0.3464185 ,  0.14702677, -0.47944804])

In [400]:
np.random.randint(1,100, 10)

array([72, 69, 24, 36, 80, 99, 68, 83, 58, 78])

In [401]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [402]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [403]:
arr = np.arange(25)

In [404]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [405]:
ranarr = np.random.randint(0,50,10)

In [406]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [407]:
arr.shape

(25,)

In [408]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [409]:
ranarr.max()

39

In [410]:
ranarr.min()

2

In [411]:
ranarr.argmax()

7

In [412]:
ranarr.argmin()

9

In [413]:
ranarr.dtype

dtype('int32')

In [414]:
arr = np.arange(0,11)

In [415]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [416]:
arr[8]

8

In [417]:
arr[1:5]

array([1, 2, 3, 4])

In [418]:
arr[0:8:2]

array([0, 2, 4, 6])

In [419]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [420]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [421]:
matrix[2,1]

40

In [422]:
matrix[2]

array([35, 40, 45])

In [423]:
matrix[2,1]

40

In [424]:
matrix[:2][1:]

array([[20, 25, 30]])

In [425]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [426]:
arr = np.arange(1,11)

In [427]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [428]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [429]:
barr = arr > 4

In [430]:
barr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [431]:
arr[barr]

array([ 5,  6,  7,  8,  9, 10])

In [432]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [433]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [434]:
arr = np.arange(0,10)

In [435]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [436]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [437]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [438]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [439]:
(arr+2)/10

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

In [440]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [441]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [442]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [443]:
1/arr

C:\Anaconda3\envs\manabuPy\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [444]:
arr/arr

C:\Anaconda3\envs\manabuPy\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [445]:
arr/(arr-arr)

C:\Anaconda3\envs\manabuPy\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Anaconda3\envs\manabuPy\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [446]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [447]:
np.log(arr)

C:\Anaconda3\envs\manabuPy\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [448]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [449]:
arr.sum()

45

In [450]:
arr.mean()

4.5

In [451]:
arr.max()

9

In [452]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [453]:
matrix.shape

(3, 4)

In [454]:
matrix.sum()

78

In [455]:
matrix.sum(axis = 0)

array([15, 18, 21, 24])

In [456]:
matrix.sum(axis = 1)

array([10, 26, 42])

In [457]:
import numpy as np
import pandas as pd

In [458]:
labels = ['a','b','c']

In [459]:
mylist = [10,20,30]

In [460]:
arr = np.array(mylist)

In [461]:
arr

array([10, 20, 30])

In [462]:
d = {'a':10,'b':20,'c':30}

In [463]:
pd.Series(data = mylist)

0    10
1    20
2    30
dtype: int64

In [464]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int32

In [465]:
pd.Series(data=[10,'a',4.4,[1,2,3]])

0           10
1            a
2          4.4
3    [1, 2, 3]
dtype: object

In [466]:
ser1 = pd.Series(data=[1,2,3,4], index=['USA','Germany','USSR','Japan'])

In [467]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [468]:
ser1['Germany']

2

In [469]:
ser2 = pd.Series(data=[1,4,5,6], index=['USA','Germany','Italy','Japan'])

In [470]:
ser2

USA        1
Germany    4
Italy      5
Japan      6
dtype: int64

In [471]:
ser1 + ser2

Germany     6.0
Italy       NaN
Japan      10.0
USA         2.0
USSR        NaN
dtype: float64

In [472]:
from numpy.random import randn
np.random.seed(101)

rand_mat = randn(5,4)

In [473]:
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [474]:
pd.DataFrame(data = rand_mat)

0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [475]:
df = pd.DataFrame(data = rand_mat, index = 'A B C D E'.split())

In [476]:
df

0         1         2         3
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [477]:
df = pd.DataFrame(data = rand_mat, index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [478]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [479]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [480]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [481]:
df['NEW'] = df['W'] + df['Y']

In [482]:
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [483]:
df.drop('NEW', axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [484]:
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [485]:
df.drop('NEW', axis=1, inplace=True)

In [486]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [487]:
df.drop('A')

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [488]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [489]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [490]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [491]:
df.loc[['A', 'C']]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001

In [492]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [493]:
df.loc[['A','B']][['X','Y','Z']]

X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [494]:
df.loc[['A','B'],['X','Y','Z']]

X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [495]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [496]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [497]:
df_bool = df>0

In [498]:
df[df_bool]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [499]:
df['W']>0.5

A     True
B     True
C    False
D    False
E    False
Name: W, dtype: bool

In [500]:
df[df['W']>0.5]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [501]:
df[(df['W'] > 0 ) & (df['Y'] > 2)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [502]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [503]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [504]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [505]:
new_ind = 'CA NY WY OR CO'.split()

In [506]:
new_ind

['CA', 'NY', 'WY', 'OR', 'CO']

In [507]:
df['States'] = new_ind

In [508]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [509]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [510]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 5 columns):
W         5 non-null float64
X         5 non-null float64
Y         5 non-null float64
Z         5 non-null float64
States    5 non-null object
dtypes: float64(4), object(1)
memory usage: 400.0+ bytes


In [511]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [512]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [513]:
df['col2'].nunique()

3

In [514]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [515]:
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [516]:
newdf

col1  col2 col3
3     4   444  xyz

In [517]:
def times_two(i):
    return i*2

In [518]:
df['new'] = df['col1'].apply(times_two)

In [519]:
df

col1  col2 col3  new
0     1   444  abc    2
1     2   555  def    4
2     3   666  ghi    6
3     4   444  xyz    8

In [520]:
del df['new']

In [521]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [522]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [523]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [524]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
col1    4 non-null int64
col2    4 non-null int64
col3    4 non-null object
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes


In [525]:
df.describe()

col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [526]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [527]:
df.sort_values(by='col2', ascending=False)

col1  col2 col3
2     3   666  ghi
1     2   555  def
0     1   444  abc
3     4   444  xyz

In [528]:
pwd

'C:\\AnCodeRR\\Project_Manabu\\PyTorch'

In [537]:
path = "C:\\AnCodeRR\\PYTORCH_NOTEBOOKS\\00-Crash-Course-Topics\\01-Crash-Course-Pandas\\example.csv"
df = pd.read_csv(path)

In [538]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [539]:
newdf = df[['a','b']]

In [540]:
newdf

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [541]:
newdf.to_csv("thisfolderexamplefile.csv", index = False)

In [542]:
mylistoftables = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [543]:
mylistoftables

[                                         Bank NameBank            CityCity  \
 0                                    Almena State Bank              Almena   
 1                           First City Bank of Florida   Fort Walton Beach   
 2                                 The First State Bank       Barboursville   
 3                                   Ericson State Bank             Ericson   
 4                     City National Bank of New Jersey              Newark   
 5                                        Resolute Bank              Maumee   
 6                                Louisa Community Bank              Louisa   
 7                                 The Enloe State Bank              Cooper   
 8                  Washington Federal Bank for Savings             Chicago   
 9      The Farmers and Merchants State Bank of Argonia             Argonia   
 10                                 Fayette County Bank          Saint Elmo   
 11   Guaranty Bank, (d/b/a BestBank in Georgia & Mi

In [544]:
len(mylistoftables)

1

In [545]:
df = mylistoftables[0]

In [546]:
df

Bank NameBank            CityCity  \
0                                    Almena State Bank              Almena   
1                           First City Bank of Florida   Fort Walton Beach   
2                                 The First State Bank       Barboursville   
3                                   Ericson State Bank             Ericson   
4                     City National Bank of New Jersey              Newark   
5                                        Resolute Bank              Maumee   
6                                Louisa Community Bank              Louisa   
7                                 The Enloe State Bank              Cooper   
8                  Washington Federal Bank for Savings             Chicago   
9      The Farmers and Merchants State Bank of Argonia             Argonia   
10                                 Fayette County Bank          Saint Elmo   
11   Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
12                                      First NBC Bank         New Orleans   
13                                       Proficio Bank  Cottonwood Heights   
14                       Seaway Bank and Trust Company             Chicago   
15                              Harvest Community Bank          Pennsville   
16                                         Allied Bank            Mulberry   
17                        The Woodbury Banking Company            Woodbury   
18                              First CornerStone Bank     King of Prussia   
19                                  Trust Company Bank             Memphis   
20                          North Milwaukee State Bank           Milwaukee   
21                              Hometown National Bank            Longview   
22                                 The Bank of Georgia      Peachtree City   
23                                        Premier Bank              Denver   
24                                      Edgebrook Bank             Chicago   
25                              Doral Bank  En Español            San Juan   
26                   Capitol City Bank & Trust Company             Atlanta   
27                             Highland Community Bank             Chicago   
28                    First National Bank of Crestview           Crestview   
29                                  Northern Star Bank             Mankato   
..                                                 ...                 ...   
533                                  ANB Financial, NA         Bentonville   
534                                          Hume Bank                Hume   
535                             Douglass National Bank         Kansas City   
536                                  Miami Valley Bank            Lakeview   
537                                            NetBank          Alpharetta   
538                          Metropolitan Savings Bank          Pittsburgh   
539                                    Bank of Ephraim             Ephraim   
540                                      Reliance Bank        White Plains   
541              Guaranty National Bank of Tallahassee         Tallahassee   
542                                Dollar Savings Bank              Newark   
543                               Pulaski Savings Bank        Philadelphia   
544              First National Bank of Blanchardville      Blanchardville   
545                              Southern Pacific Bank            Torrance   
546                        Farmers Bank of Cheneyville         Cheneyville   
547                                      Bank of Alamo               Alamo   
548             AmTrade International Bank  En Español             Atlanta   
549                     Universal Federal Savings Bank             Chicago   
550                       Connecticut Bank of Commerce            Stamford   
551                                   New Century Bank     Shelby Township   
552                              Net 1st National Bank         