In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
torch.__version__

'1.1.0'

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int32')

In [6]:
type(arr)

numpy.ndarray

In [7]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
ten = torch.from_numpy(arr)

In [9]:
ten

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [10]:
type(ten)

torch.Tensor

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
matrix = np.arange(0.0, 12.0)

In [13]:
matrix

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
matrix = matrix.reshape(4,3)

In [15]:
matrix

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
ten2d = torch.from_numpy(matrix)

In [17]:
ten2d

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
ten

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [20]:
arr[0] = 99

In [21]:
arr

array([99,  2,  3,  4,  5])

In [22]:
ten

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [23]:
myarr = np.arange(0, 10)

In [24]:
myarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
mytensor = torch.tensor(myarr)

In [26]:
mytensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [27]:
myothertensor = torch.from_numpy(myarr)

In [28]:
myarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
mytensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [30]:
myothertensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [31]:
myarr[0] = 99

In [32]:
myarr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [33]:
mytensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [34]:
myothertensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [35]:
newarr = np.array([1,2,3])

In [36]:
newarr.dtype

dtype('int32')

In [37]:
torch.tensor(newarr)

tensor([1, 2, 3], dtype=torch.int32)

In [38]:
ten = torch.Tensor(newarr)

In [39]:
ten.dtype

torch.float32

In [40]:
torch.empty(4,2)

tensor([[6.7382e-10, 1.3297e+22],
        [3.3089e-09, 6.5191e-10],
        [3.3855e-06, 1.6997e-04],
        [1.0514e-05, 4.2657e-08]])

In [41]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [42]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [43]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [44]:
mytensor = torch.tensor([1,2,3,4,5])

In [45]:
mytensor.dtype

torch.int64

In [46]:
mytensor = mytensor.type(torch.int32)

In [47]:
mytensor

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [48]:
torch.rand(4,3)

tensor([[0.2843, 0.8927, 0.7745],
        [0.3552, 0.1502, 0.2315],
        [0.4053, 0.5021, 0.7457],
        [0.4063, 0.0906, 0.6630]])

In [49]:
torch.randn(4,3)

tensor([[ 0.5696, -0.5875,  0.2025],
        [-1.1442, -1.7631,  0.9319],
        [-0.3758,  0.0674, -0.9360],
        [-0.3308,  1.3049, -0.0160]])

In [50]:
torch.randint(low=1, high=10, size=(5,5))

tensor([[2, 7, 6, 7, 2],
        [1, 3, 7, 3, 5],
        [2, 3, 8, 1, 1],
        [5, 8, 9, 6, 3],
        [2, 7, 1, 5, 9]])

In [51]:
x = torch.zeros(2,5)

In [52]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [53]:
x.shape

torch.Size([2, 5])

In [54]:
torch.rand_like(x)

tensor([[0.8407, 0.7926, 0.7047, 0.0535, 0.1829],
        [0.6756, 0.7230, 0.7332, 0.2854, 0.8452]])

In [55]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [56]:
x=torch.arange(6).reshape(3,2)

In [57]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [58]:
x[1,1]

tensor(3)

In [59]:
x[:,1]

tensor([1, 3, 5])

In [60]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [61]:
x = torch.arange(10)

In [62]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [64]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [66]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x.shape

torch.Size([10])

In [68]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
z = x.view(2,5)

In [70]:
x[0] = 9999

In [71]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [72]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [73]:
x = torch.arange(10)

In [74]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [76]:
a = torch.tensor([1.,2.,3.])

In [77]:
b = torch.tensor([4.,5.,6.])

In [78]:
a+b

tensor([5., 7., 9.])

In [79]:
a

tensor([1., 2., 3.])

In [80]:
b

tensor([4., 5., 6.])

In [81]:
a-b

tensor([-3., -3., -3.])

In [82]:
a*b

tensor([ 4., 10., 18.])

In [83]:
a/b

tensor([0.2500, 0.4000, 0.5000])

In [84]:
a//b

tensor([0., 0., 0.])

In [85]:
a**b

tensor([  1.,  32., 729.])

In [86]:
torch.add(a,b)

tensor([5., 7., 9.])

In [87]:
torch.sub(a,b)

tensor([-3., -3., -3.])

In [88]:
a

tensor([1., 2., 3.])

In [89]:
a.add_(b)

tensor([5., 7., 9.])

In [90]:
a

tensor([5., 7., 9.])

In [91]:
a = torch.tensor([1., 2., 3.])

In [92]:
b = torch.tensor([4., 5., 6.])

In [93]:
a

tensor([1., 2., 3.])

In [94]:
b

tensor([4., 5., 6.])

In [95]:
a*b

tensor([ 4., 10., 18.])

In [96]:
a.dot(b)

tensor(32.)

In [97]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [98]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [99]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [100]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [101]:
a.shape

torch.Size([2, 3])

In [102]:
b.shape

torch.Size([3, 2])

In [103]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [104]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [105]:
x = torch.tensor([2., 3., 4., 5.])

In [106]:
x

tensor([2., 3., 4., 5.])

In [107]:
x.norm()

tensor(7.3485)

In [108]:
x.numel()

4

In [109]:
len(x)

4

In [110]:
len(a)

2

In [111]:
a.numel()

6