In [1]:
import numpy as np

# Basic NP Array Initialization:

In [2]:
a = np.array([1,2,3])
b = np.array([[9.0,8.0,7.8],[6.0,5.3,3.0]], dtype='float32')
print(a)
print(b)

[1 2 3]
[[9.  8.  7.8]
 [6.  5.3 3. ]]


# Useful NP Array Attributes:
# np.ndarray.ndim, .shape, .size, .dtype, .itemsize, .nbytes

In [3]:
print('Number of dimensions:')
print('for a:', a.ndim)
print('for b:', b.ndim)
print('Shape of array:')
print('for a:',a.shape)
print('for b:',b.shape)
print('Number of elements:')
print('for a:',a.size)
print('for b:',b.size)
print('Datatype for the array:')
print('for a:',a.dtype)
print('for b:',b.dtype)
print('Item size for each element in bytes:')
print('for a:',a.itemsize)
print('for b:',b.itemsize)
print('Total number of bytes consumed:')
print('for a:',a.nbytes)
print('for b:',b.nbytes)

Number of dimensions:
for a: 1
for b: 2
Shape of array:
for a: (3,)
for b: (2, 3)
Number of elements:
for a: 3
for b: 6
Datatype for the array:
for a: int32
for b: float32
Item size for each element in bytes:
for a: 4
for b: 4
Total number of bytes consumed:
for a: 12
for b: 24


# NP Array Indexing:

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a[1,5])
print(a[:,5])
print(a[1,:])
print(a[:,1:5:2]) # start_index, end_index, step_size

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[ 6 13]
[ 8  9 10 11 12 13 14]
[[ 2  4]
 [ 9 11]]


# NP Array Changing Specific Values:

In [5]:
a[1,2:6] = 1
print(a)
a[1,2:6] = [21,22,23,24]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9  1  1  1  1 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 21 22 23 24 14]]


# NP Array Initialization Advanced:

In [6]:
print(np.zeros((2,3,4)))
print(np.ones((2,3), dtype='int16'))
print(np.full((2,3), 13, dtype='float32'))
print(np.identity(3))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1 1 1]
 [1 1 1]]
[[13. 13. 13.]
 [13. 13. 13.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
print(np.zeros_like(a))
print(np.ones_like(a))
print(np.full_like(a, 99))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
[[99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]]


In [8]:
print(np.random.rand(2,3))
print(np.random.randint(-5, 6, size=(3,5)))
print(np.random.random_sample(b.shape))

[[0.61994594 0.65921774 0.84224777]
 [0.65240216 0.78960575 0.87748177]]
[[ 2  0  0 -3  2]
 [ 1 -2  2  4 -3]
 [-1  5  2 -2 -1]]
[[0.54473468 0.95746988 0.50087456]
 [0.36076962 0.27838526 0.55734444]]


In [9]:
arr = np.array([1,2,3])
print(np.repeat(arr, 3, axis=0))
arr = np.array([[1,2,3]])
print(np.repeat(arr, 3, axis=0))

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
output = np.ones((5,5), dtype='int32')
output[1:4, 1:4] = 0
output[2,2] = 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# NP Array Passing:
### Copying array leads to changes being made to one translating to the other array.

In [11]:
a = np.array([1,2,3])
b = a
print(a)
print(b)
b[0] = 100
print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


# NP Array Copying:
### Copying array doesnt lead to changes being made to one translating to the other array.

In [12]:
a = np.array([1,2,3])
b = a.copy()
print(a)
print(b)
b[0] = 100
print(a)
print(b)

[1 2 3]
[1 2 3]
[1 2 3]
[100   2   3]


# NP Array Arithmetic Operations:

In [13]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a%2)
print(a**2)
print(a*b)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[1 0 1 0]
[ 1  4  9 16]
[ 5 12 21 32]


# NP Array Trigonometric Operations:

In [14]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.sinh(a))
print(np.cosh(a))
print(np.tanh(a))
print(np.arcsin(0.75))
print(np.arccos(0.75))
print(np.arctanh(0.75))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[ 1.17520119  3.62686041 10.01787493 27.2899172 ]
[ 1.54308063  3.76219569 10.067662   27.30823284]
[0.76159416 0.96402758 0.99505475 0.9993293 ]
0.848062078981481
0.7227342478134157
0.9729550745276566


# NP Array Linear Algebra

In [15]:
a = np.full((2,3),1)
b = np.full((3,2),2)
c = np.identity(3)
print(a)
print(b)
print(np.matmul(a,b))
print(np.linalg.det(c))
# For more Linear Algebra Operations with Numpy
# https://numpy.org/doc/stable/reference/routines.linalg.html
# Determinant, Trace, Eigenvalues, Matrix Norm, Inverse

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]
1.0


# NP Array Statistics:
# np.min(), np.max(), np.sum()

In [16]:
a = np.array([[10,11,12],[30,15,20]])
print(a)
print(np.min(a))
print(np.min(a, axis=1))
print(np.min(a, axis=0))
print(np.max(a))

[[10 11 12]
 [30 15 20]]
10
[10 15]
[10 11 12]
30


# NP Array Reorganizing and Reshaping:
# np.ndarray.reshape(), np.vstack(), np.hstack():

In [17]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a,'\n')

print(a.reshape((1,8)),'\n')
print(a.reshape((-1,8)),'\n')
print(a.reshape((1,-1)),'\n')
print(a.reshape((4,2)),'\n')
print(a.reshape((2,2,2)))

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2 3 4 5 6 7 8]] 

[[1 2 3 4 5 6 7 8]] 

[[1 2 3 4 5 6 7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([11,12,13,14,15])
c = np.array([[11,12,13,14,15],[16,17,18,19,20]])
print(np.vstack((a,b)))
print(np.hstack((a,c)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
