In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../Data/Data.csv')
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [3]:
column_names = list(df.columns)
print(column_names)

['Country', 'Age', 'Salary', 'Purchased']


In [4]:
print(df['Age'].to_numpy().reshape((1,-1)))
print(type(df))
print(type(df['Age']))
print(type(df.iloc[:,:]))
print(type(df[['Age', 'Salary']]))

[[44. 27. 30. 38. 40. 35. nan 48. 50. 37.]]
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [5]:
x = df.iloc[:,:-1]
print(x)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [6]:
x = df.iloc[:,:-1].values
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
y = df.iloc[:,-1].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8)

In [12]:
print("Train X\n", x_train)
print("Test X\n", x_test)
print("Train Y\n", y_train)
print("Test Y\n", y_test)

Train X
 [[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]
Test X
 [[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]]
Train Y
 [0 1 0 1 0 1 1 0]
Test Y
 [0 1]


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])
print("Train X\n", x_train)
print("Test X\n", x_test)

Train X
 [[0.0 1.0 0.0 -1.561515133405723 -1.022395495617914]
 [0.0 1.0 0.0 0.06553392021529096 -0.09005556179017836]
 [0.0 0.0 1.0 -0.2598758905089118 -0.35492486117305805]
 [1.0 0.0 0.0 -0.747990606595216 -0.6409837045065677]
 [0.0 1.0 0.0 1.692582973836305 1.7428399899393465]
 [1.0 0.0 0.0 -0.4225807958710132 0.21719282549396138]
 [1.0 0.0 0.0 1.367173163112102 1.3614281988280001]
 [0.0 0.0 1.0 -0.13332763078283283 -1.213101391173587]]
Test X
 [[1.0 0.0 0.0 0.7163535416636966 0.6939575643831442]
 [0.0 0.0 1.0 -2.0496298494920273 -1.5945131822849334]]


In [31]:
nums = [9,1,8,2,7,3,6,4]
x = 40
target = sum(nums) - x
ans = -1
s = l = 0
n = len(nums)
for r in range(n):
    s += nums[r]
    while s > target and l <= r:
        s -= nums[l]
        l += 1
    if s == target:
        ans = min(ans, n - (r - l + 1))
print(ans if ans != -1 else -1)

KeyboardInterrupt: 